import uuid
from sqlalchemy import Column, String, Text, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from app.db.base import Base


class Draft(Base):
    """Persisted outreach draft linked to a company and optionally a signal.

    Drafts are generated by the Outreach Strategy Agent and can be
    edited by the user. The lifecycle tracks: in_progress → sent | discarded.
    """
    __tablename__ = "drafts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    company_kb_id = Column(
        UUID(as_uuid=True),
        ForeignKey("company_knowledge_base.id", ondelete="CASCADE"),
        nullable=False,
    )
    signal_id = Column(
        UUID(as_uuid=True),
        ForeignKey("signal_events.id", ondelete="SET NULL"),
        nullable=True,
    )
    contact_name = Column(String(500))
    contact_title = Column(String(500))
    format = Column(String(20), nullable=False)  # email, linkedin
    tone = Column(String(20), default="direct")  # direct, consultative, formal, casual
    voice_profile = Column(String(20), default="concise")  # concise, consultative, formal
    subject = Column(String(500))
    body = Column(Text, nullable=False)
    hooks_used = Column(JSONB, default=[])  # Signal references used in draft
    status = Column(String(20), default="in_progress")  # in_progress, sent, discarded
    sent_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    __table_args__ = (
        Index("ix_draft_company", "company_kb_id", "created_at"),
        Index("ix_draft_status", "status"),
    )
