"""add_pipeline_logs_and_bant_sources

Revision ID: 526a00746466
Revises: ad6870bc307f
Create Date: 2026-03-03 03:22:06.183928

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '526a00746466'
down_revision: Union[str, None] = 'ad6870bc307f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_logs_pipeline_run_id'), 'pipeline_logs', ['pipeline_run_id'], unique=False)
    op.add_column('bant_scores', sa.Column('budget_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bant_scores', sa.Column('authority_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bant_scores', sa.Column('need_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('bant_scores', sa.Column('timing_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bant_scores', 'timing_sources')
    op.drop_column('bant_scores', 'need_sources')
    op.drop_column('bant_scores', 'authority_sources')
    op.drop_column('bant_scores', 'budget_sources')
    op.drop_index(op.f('ix_pipeline_logs_pipeline_run_id'), table_name='pipeline_logs')
    op.drop_table('pipeline_logs')
    # ### end Alembic commands ###
