"""Add asset_value to companies

Revision ID: 704565025b67
Revises: c0b6b9bba9b6
Create Date: 2026-03-13 11:12:12.780031

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '704565025b67'
down_revision: Union[str, None] = 'c0b6b9bba9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('asset_value', sa.BigInteger(), nullable=True))
    op.drop_index('idx_companies_embedding', table_name='companies', postgresql_using='hnsw')
    op.drop_index('ix_companies_website', table_name='companies')
    op.drop_index('ix_company_stage_results_company_id', table_name='company_stage_results')
    op.drop_index('ix_company_stage_results_stage', table_name='company_stage_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_company_stage_results_stage', 'company_stage_results', ['stage'], unique=False)
    op.create_index('ix_company_stage_results_company_id', 'company_stage_results', ['company_id'], unique=False)
    op.create_index('ix_companies_website', 'companies', [sa.text('lower(website::text)')], unique=False)
    op.create_index('idx_companies_embedding', 'companies', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_column('companies', 'asset_value')
    # ### end Alembic commands ###
