"""Initial schema with pgvector

Revision ID: ad6870bc307f
Revises: 
Create Date: 2026-02-25 12:28:39.170400

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad6870bc307f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icp_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('icp_config_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('companies_found', sa.Integer(), nullable=True),
    sa.Column('contacts_found', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.Column('stage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['icp_config_id'], ['icp_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('sub_industry', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state_region', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue_estimate', sa.BigInteger(), nullable=True),
    sa.Column('tech_stack_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=500), nullable=True),
    sa.Column('qualification', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('icp_match_score', sa.Float(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('designation', sa.String(length=500), nullable=True),
    sa.Column('role_category', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('enrichment_status', sa.String(length=50), nullable=True),
    sa.Column('raw_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bant_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('budget_score', sa.Integer(), nullable=True),
    sa.Column('budget_reason', sa.Text(), nullable=True),
    sa.Column('authority_score', sa.Integer(), nullable=True),
    sa.Column('authority_reason', sa.Text(), nullable=True),
    sa.Column('need_score', sa.Integer(), nullable=True),
    sa.Column('need_reason', sa.Text(), nullable=True),
    sa.Column('timing_score', sa.Integer(), nullable=True),
    sa.Column('timing_reason', sa.Text(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('overall_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bant_scores')
    op.drop_table('contacts')
    op.drop_table('companies')
    op.drop_table('pipeline_runs')
    op.drop_table('icp_configs')
    # ### end Alembic commands ###
